# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome_admin', '0010_auto_20151202_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.RemoveField(
            model_name='socket',
            name='attached_device',
        ),
        migrations.RemoveField(
            model_name='temperaturerecord',
            name='controller',
        ),
        migrations.AddField(
            model_name='smarthomecontroller',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='socket',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='temperaturerecord',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='controllercapability',
            name='control_class',
            field=models.CharField(choices=[['Sockets', 'Sockets'], ['Temperature', 'Temperature'], ['RemoteControl', 'RemoteControl']], max_length=1024),
        ),
        migrations.AddField(
            model_name='temperaturezone',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome_admin.SmartHomeController'),
        ),
        migrations.AddField(
            model_name='temperaturerecord',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smarthome_admin.TemperatureZone'),
        ),
    ]
